ru:
  languageCode: ru-RU
  contentDir: content/ru
  languageName: Русский
  title: Карпухин Клим
  weight: 1
  params:
    description: Персональный сайт Карпухина Клима (РУДН)
    hugoblox:
      identity:
        name: Карпухин Клим
        organization: РУДН
        tagline: "Студент, исследователь"
        social:
          github: Kreazot316
  menu:
    main:
      - name: "Обо мне"
        url: "/"
        weight: 10
      - name: "Опыт"
        url: "/experience/"
        weight: 20
      - name: "Проекты"
        url: "/projects/"
        weight: 30
